name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^6.2.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  flutter_compass: '^0.7.0'
  permission_handler: ^5.1.0+2
  shake: ^1.0.1

#  test
  image_picker: ^0.8.0+4
  video_player: ^2.2.19
  google_fonts: ^2.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900